Post http://localhost:3003/api/blogs/6355a115fe21caf596630b5a/comment
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ill1aSIsImlkIjoiNjMzYjljM2E2ZjZiMDgzYmQ3M2QyOGZkIiwiaWF0IjoxNjY0ODg3ODM1fQ.KEWa_NqFWxFh-u9qy9FGPbAkbaPPWUKpoYUzf5Vpw8g

{
    "id": "6355c332402a72a157b78bc0",
    "title":"React Hooks vs Redux – You Might Not Need Redux",
    "author":"Mike Green",
    "url":"https://www.simplethread.com/cant-replace-redux-with-hooks/",
    "likes": 1,
    "user": "633b9c3a6f6b083bd73d28fd",
    "comments":["A good article", "Really helpful!"]
}